name: prod-ci-roles

on:
  push:
    paths: 
      - 'environments/prod/global/**'
      - '.github/workflows/**-prod.yml'

jobs:
  terragrunt:
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    uses: kloud-cnf/workflows/.github/workflows/terragrunt.yaml@v0.3.2
    with:
      working-directory: "environments/prod/global/"
      target-account-id: "310394544294"
      target-region: "eu-west-1"
      ci-role-name: "github-ci-role-provisioner"
